import type { ReactNode } from 'react';
import {
  CubeIcon,
  LayersIcon,
  RocketIcon,
  Pencil2Icon,
  PersonIcon,
  LockClosedIcon,
  GearIcon,
  GlobeIcon,
  ArchiveIcon,
  DesktopIcon,
  Link2Icon,
  BarChartIcon,
  CheckCircledIcon,
  FileIcon,
  StackIcon,
  DashboardIcon,
  BellIcon,
  ActivityLogIcon,
} from '@radix-ui/react-icons';
import HelmIcon from '../components/icons/HelmIcon';
import CrossplaneIcon from '../components/icons/CrossplaneIcon';
import ArgoIcon from '../components/icons/ArgoIcon';

type IconRenderer = ReactNode;

export const getResourceIcon = (kind: string): IconRenderer => {
  const kindLower = kind.toLowerCase();

  const iconMap: Record<string, IconRenderer> = {
    clusterdashboard: <DashboardIcon />,
    overview: <DashboardIcon />,
    finopsdashboard: <ActivityLogIcon />,
    finops: <ActivityLogIcon />,
    event: <BellIcon />,
    events: <BellIcon />,
    pod: <CubeIcon />,
    pods: <CubeIcon />,
    deployment: <LayersIcon />,
    deployments: <LayersIcon />,
    replicaset: <StackIcon />,
    replicasets: <StackIcon />,
    statefulset: <ArchiveIcon />,
    statefulsets: <ArchiveIcon />,
    daemonset: <RocketIcon />,
    daemonsets: <RocketIcon />,
    job: <RocketIcon />,
    jobs: <RocketIcon />,
    cronjob: <RocketIcon />,
    cronjobs: <RocketIcon />,
    service: <Link2Icon />,
    services: <Link2Icon />,
    ingress: <GlobeIcon />,
    ingresses: <GlobeIcon />,
    networkpolicy: <LockClosedIcon />,
    networkpolicies: <LockClosedIcon />,
    configmap: <GearIcon />,
    configmaps: <GearIcon />,
    secret: <LockClosedIcon />,
    secrets: <LockClosedIcon />,
    persistentvolume: <ArchiveIcon />,
    persistentvolumes: <ArchiveIcon />,
    persistentvolumeclaim: <FileIcon />,
    persistentvolumeclaims: <FileIcon />,
    storageclass: <ArchiveIcon />,
    storageclasses: <ArchiveIcon />,
    namespace: <FileIcon />,
    namespaces: <FileIcon />,
    node: <DesktopIcon />,
    nodes: <DesktopIcon />,
    serviceaccount: <PersonIcon />,
    serviceaccounts: <PersonIcon />,
    role: <Pencil2Icon />,
    roles: <Pencil2Icon />,
    clusterrole: <Pencil2Icon />,
    clusterroles: <Pencil2Icon />,
    rolebinding: <Link2Icon />,
    rolebindings: <Link2Icon />,
    clusterrolebinding: <Link2Icon />,
    clusterrolebindings: <Link2Icon />,
    horizontalpodautoscaler: <BarChartIcon />,
    horizontalpodautoscalers: <BarChartIcon />,
    hpa: <BarChartIcon />,
    verticalpodautoscaler: <BarChartIcon />,
    verticalpodautoscalers: <BarChartIcon />,
    vpa: <BarChartIcon />,
    poddisruptionbudget: <CheckCircledIcon />,
    poddisruptionbudgets: <CheckCircledIcon />,
    pdb: <CheckCircledIcon />,
    limitrange: <BarChartIcon />,
    limitranges: <BarChartIcon />,
    resourcequota: <BarChartIcon />,
    resourcequotas: <BarChartIcon />,
    endpoint: <Link2Icon />,
    endpoints: <Link2Icon />,
    endpointslice: <Link2Icon />,
    endpointslices: <Link2Icon />,
    mutatingwebhookconfiguration: <GearIcon />,
    mutatingwebhookconfigurations: <GearIcon />,
    validatingwebhookconfiguration: <CheckCircledIcon />,
    validatingwebhookconfigurations: <CheckCircledIcon />,
    customresourcedefinition: <GearIcon />,
    customresourcedefinitions: <GearIcon />,
    crd: <GearIcon />,
    priorityclass: <BarChartIcon />,
    priorityclasses: <BarChartIcon />,
    certificate: <FileIcon />,
    certificates: <FileIcon />,
    issuer: <FileIcon />,
    issuers: <FileIcon />,
    clusterissuer: <FileIcon />,
    clusterissuers: <FileIcon />,
  };

  return iconMap[kindLower] || <FileIcon />;
};

export const getCategoryIcon = (category: string): IconRenderer => {
  const categoryLower = category.toLowerCase();

  const categoryMap: Record<string, IconRenderer> = {
    workloads: <GearIcon />,
    config: <GearIcon />,
    configs: <GearIcon />,
    network: <GlobeIcon />,
    networking: <GlobeIcon />,
    storage: <ArchiveIcon />,
    rbac: <LockClosedIcon />,
    cluster: <CubeIcon />,
    'custom resources': <GearIcon />,
    customresources: <GearIcon />,
    custom: <GearIcon />,
    kanivetide: <CubeIcon />,
    package: <ArchiveIcon />,
    folder: <FileIcon />,
    helm: <HelmIcon />,
    'helm releases': <HelmIcon />,
    finops: <ActivityLogIcon />,
    crossplane: <CrossplaneIcon />,
    argocd: <ArgoIcon />,
    'argo cd': <ArgoIcon />,
    argo: <ArgoIcon />,
    vclusters: <LayersIcon />,
    'virtual clusters': <LayersIcon />,
    vcluster: <LayersIcon />,
  };

  return categoryMap[categoryLower] || <FileIcon />;
};
